# Generated by Django 3.2.12 on 2023-03-02 05:23

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_titile', models.CharField(max_length=100)),
                ('Blog_msg', tinymce.models.HTMLField()),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
