# Generated by Django 3.2.12 on 2023-03-02 05:53

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Blog_titile',
            field=tinymce.models.HTMLField(),
        ),
    ]
