# Generated by Django 3.2.12 on 2023-03-05 06:13

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blog_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
        migrations.AddField(
            model_name='blog',
            name='Blog_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='Blog_titile', unique=True),
        ),
    ]
