# Generated by Django 3.2.12 on 2023-03-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_blog_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Blog_img',
            field=models.FileField(default=None, max_length=500, null=True, upload_to='Blog/'),
        ),
    ]
