# Generated by Django 3.2.12 on 2023-03-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_blog_blog_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Blog_img1',
            field=models.FileField(default=None, max_length=500, null=True, upload_to='Blog/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='Blog_img2',
            field=models.FileField(default=None, max_length=500, null=True, upload_to='Blog/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='Blog_img3',
            field=models.FileField(default=None, max_length=500, null=True, upload_to='Blog/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='Blog_img4',
            field=models.FileField(default=None, max_length=500, null=True, upload_to='Blog/'),
        ),
    ]
