# Generated by Django 3.2.12 on 2023-03-06 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20230306_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='datetime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 3, 6, 15, 52, 1, 98655)),
        ),
    ]
