# Generated by Django 3.2.12 on 2023-03-06 10:29

import autoslug.fields
import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apps_titile', tinymce.models.HTMLField()),
                ('Apps_msg', tinymce.models.HTMLField()),
                ('datetime', models.DateTimeField(verbose_name=datetime.datetime(2023, 3, 6, 15, 59, 17, 70285))),
                ('Apps_img', models.FileField(default=None, max_length=500, null=True, upload_to='Apps/')),
                ('Apps_img1', models.FileField(default=None, max_length=500, null=True, upload_to='Apps/')),
                ('Apps_img2', models.FileField(default=None, max_length=500, null=True, upload_to='Apps/')),
                ('Apps_img3', models.FileField(default=None, max_length=500, null=True, upload_to='Apps/')),
                ('Apps_img4', models.FileField(default=None, max_length=500, null=True, upload_to='Apps/')),
                ('Apps_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='Apps_titile', unique=True)),
            ],
        ),
    ]
