# Generated by Django 3.2.12 on 2023-03-06 13:34

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_apps_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='Apps_links',
            field=tinymce.models.HTMLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='apps',
            name='datetime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 3, 6, 19, 4, 37, 504593)),
        ),
    ]
